import type { ApiRequestHandler } from "../types/api.js";
import { successResponse } from "../types/api.js";
import { generatePrdSchema, getPrdParamsSchema } from "../schemas/prd.schema.js";

const mockMarkdownPrd = `# Product Requirements Document
# Mock Product PRD

**Version:** 1.0.0
**Status:** Draft
**Author:** AI Generated by SpecPilot AI
**Last Updated:** 2026-06-05
**Confidentiality:** Public

---

## 1. Executive Summary

Mock Product helps users clarify a rough idea into an execution-ready MVP plan. This mock PRD demonstrates visual Markdown output required by SpecPilot AI.

## 2. Product Overview

| Field | Description |
|---|---|
| Product type | Web app |
| Primary users | Builders validating MVP scope |
| Core value | Turns vague ideas into structured implementation context |
| MVP outcome | Guided interview plus visual PRD output |

## 3. MVP Scope

| Feature | Priority | Effort | Impact |
|---|---:|---:|---:|
| Idea intake | P0 | Low | High |
| Interview wizard | P0 | Medium | High |
| Visual PRD generation | P0 | Medium | High |
| Public share links | Out of scope | Medium | Low |

## 4. Main User Flow

\`\`\`mermaid
flowchart TD
    A[User enters rough idea] --> B[Backend creates project session]
    B --> C[Interview wizard asks focused question]
    C --> D[User selects option or Custom]
    D --> E[Backend validates and saves answer]
    E --> F{Ready to generate?}
    F -- No --> C
    F -- Yes --> G[Generate visual Markdown PRD]
    G --> H[User copies or downloads PRD]
\`\`\`

## 5. Data Model

\`\`\`mermaid
erDiagram
    PROJECTS ||--o{ INTERVIEW_ANSWERS : has
    PROJECTS ||--|| GENERATED_PRDS : produces

    PROJECTS {
        uuid id PK
        uuid session_id UK
        text raw_idea
        text status
        numeric current_completeness_score
    }

    INTERVIEW_ANSWERS {
        uuid id PK
        uuid project_id FK
        int sequence_number
        text question
        text answer_value
    }

    GENERATED_PRDS {
        uuid id PK
        uuid project_id FK
        text markdown_content
    }
\`\`\`

## 6. Timeline

\`\`\`mermaid
gantt
    title Mock Product MVP Timeline
    dateFormat  YYYY-MM-DD
    section Foundation
    Backend scaffold      :done, a1, 2026-06-05, 2d
    Database schema       :a2, after a1, 2d
    section AI Core
    Interview provider    :b1, after a2, 3d
    PRD generation        :b2, after b1, 3d
    section Frontend
    Wizard UI             :c1, after b1, 4d
    PRD renderer          :c2, after b2, 3d
\`\`\`

## 7. Requirement Completeness Model

\`\`\`mermaid
pie title Requirement Completeness Weight
    "MVP scope" : 20
    "Problem clarity" : 15
    "Target users" : 15
    "User flow" : 10
    "Data model" : 10
    "Technical constraints" : 10
    "Success metrics" : 10
    "Risks / sensitivity" : 5
    "Differentiator" : 5
\`\`\`

| Dimension | Weight | Mock score |
|---|---:|---:|
| Problem clarity | 15 | 12 |
| Target users | 15 | 10 |
| MVP scope | 20 | 14 |
| User flow | 10 | 8 |
| Data model | 10 | 7 |
| Technical constraints | 10 | 7 |
| Success metrics | 10 | 6 |
| Risks / sensitivity | 5 | 3 |
| Differentiator | 5 | 3 |

## 8. Feature Priority Matrix

| Feature | User value | Technical effort | Priority |
|---|---:|---:|---|
| Idea intake | High | Low | P0 |
| Interview wizard | High | Medium | P0 |
| Visual Markdown PRD | High | Medium | P0 |
| Authentication | Medium | High | Later |

## 9. Risks & Mitigations

| Risk | Likelihood | Impact | Mitigation |
|---|---|---|---|
| AI returns invalid JSON | Medium | High | Validate with Zod and repair once |
| PRD output becomes generic | Medium | High | Require interview context before generation |
| Mermaid rendering fails | Medium | Medium | Keep raw Mermaid code visible |
| Secret leakage | Low | Critical | Keep AI calls and keys backend-only |

## 10. AI Coding Agent Prompt

Build the MVP according to this PRD. Preserve backend-only AI calls, Zod validation, anonymous session flow, and visual Markdown output with Mermaid diagrams. Do not add authentication or public share links in this phase.
`;

export const generatePrd: ApiRequestHandler = (req, res) => {
  const input = generatePrdSchema.parse(req.body);

  res.status(201).json(
    successResponse({
      prd_id: "mock-prd-id",
      project_id: input.project_id,
      session_id: input.session_id,
      markdown_content: mockMarkdownPrd,
      provider_used: "mock",
      model_used: "mock-mode"
    })
  );
};

export const getPrd: ApiRequestHandler = (req, res) => {
  const params = getPrdParamsSchema.parse(req.params);

  res.json(
    successResponse({
      prd_id: "mock-prd-id",
      project_id: "mock-project-id",
      session_id: params.session_id,
      markdown_content: mockMarkdownPrd,
      provider_used: "mock",
      model_used: "mock-mode"
    })
  );
};
